defaults:
  -
    scope:
      path: "guides"
    values:
      layout: "guides"
  -
    scope:
      path: "projects"
    values:
      layout: "projects"
      isProject: true
include: [README.md,CONTRIBUTING.md]
permalink: pretty
